- name: "CIS 1.7 - Configure Login Banners"
  tags:
    - cis_1.7
  block:

    # 1.7.1 - MOTD
    - name: "Ensure message of the day is configured"
      ansible.builtin.copy:
        dest: /etc/motd
        content: "{{ cis_warning_banner }}"
        owner: root
        group: root
        mode: '0644'
      tags:
        - cis_1.7.1
        - level1

    # 1.7.2 - Local login banner
    - name: "Ensure /etc/issue is configured"
      ansible.builtin.copy:
        dest: /etc/issue
        content: "{{ cis_warning_banner }}"
        owner: root
        group: root
        mode: '0644'
      tags:
        - cis_1.7.2
        - level1

    # 1.7.3 - Remote login banner
    - name: "Ensure /etc/issue.net is configured"
      ansible.builtin.copy:
        dest: /etc/issue.net
        content: "{{ cis_warning_banner }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart sshd
      tags:
        - cis_1.7.3
        - level1

    # 1.7.4
    - name: "Ensure permissions on /etc/motd"
      ansible.builtin.file:
        path: /etc/motd
        owner: root
        group: root
        mode: '0644'
      tags:
        - cis_1.7.4

    # 1.7.5
    - name: "Ensure permissions on /etc/issue"
      ansible.builtin.file:
        path: /etc/issue
        owner: root
        group: root
        mode: '0644'
      tags:
        - cis_1.7.5

    # 1.7.6
    - name: "Ensure permissions on /etc/issue.net"
      ansible.builtin.file:
        path: /etc/issue.net
        owner: root
        group: root
        mode: '0644'
      tags:
        - cis_1.7.6
