cis_sshd_settings:
  - { regexp: '^Ciphers', line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr' }
  - { regexp: '^KexAlgorithms', line: 'KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256' }
  - { regexp: '^MACs', line: 'MACs hmac-sha2-512,hmac-sha2-256' }
  - { regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300' }
  - { regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 3' }
  - { regexp: '^DisableForwarding', line: 'DisableForwarding yes' }
  - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }
  - { regexp: '^HostbasedAuthentication', line: 'HostbasedAuthentication no' }
  - { regexp: '^IgnoreRhosts', line: 'IgnoreRhosts yes' }
  - { regexp: '^LoginGraceTime', line: 'LoginGraceTime 60' }
  - { regexp: '^LogLevel', line: 'LogLevel VERBOSE' }
  - { regexp: '^MaxAuthTries', line: 'MaxAuthTries 4' }
  - { regexp: '^MaxStartups', line: 'MaxStartups 10:30:60' }
  - { regexp: '^MaxSessions', line: 'MaxSessions 10' }
  - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
  - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
  - { regexp: '^PermitUserEnvironment', line: 'PermitUserEnvironment no' }
  - { regexp: '^UsePAM', line: 'UsePAM yes' }
