- name: "CIS 6.3.3 - Deploy audit rules"
  ansible.builtin.copy:
    dest: /etc/audit/rules.d/cis.rules
    content: |
      {% for rule in cis_audit_rules %}
      {{ rules }}
      {% endfor %}
    owner: root
    group: root
    mode: '0600'
  notify: Reload auditd
  tags:
    - cis_6.3.3

- name: "Reload audit rules"
  ansible.builtin.command: augenrules --load
  changed_when: false
  notify: Restart auditd
  tags:
    - cis_6.3.3
