- name: "Ensure auditd packages are installed"
  ansible.builtin.yum:
    name: audit
    state: present
  tags:
    - cis_6.3.1.1

- name: "Ensure auditing for processes that start prior to auditd is enabled"
  ansible.builtin.sysctl:
    name: kernel.audit
    value: '1'
    state: present
    reload: yes
  tags:
    - cis_6.3.1.2

- name: "Ensure audit_backlog_limit is sufficient"
  ansible.builtin.sysctl:
    name: fs.audit.backlog_limit
    value: '8192'
    state: present
    reload: yes
  tags:
    - cis_6.3.1.3

- name: "Ensure auditd service is enabled and active"
  ansible.builtin.systemd:
    name: auditd
    enabled: yes
    state: started
  tags:
    - cis_6.3.1.4
