---
- name: SSH - Disable Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart SSH

- name: SSH - Disable Root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: SSH - Enforce Protocol 2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol'
    line: 'Protocol 2'
  notify: Restart SSH

- name: Enable challenge-response authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication yes'
  notify: Restart SSH

- name: Enable PAM in SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    line: 'UsePAM yes'
  notify: Restart SSH
