- name: "CIS 5.1.1 - Ensure permissions are on sshd_config"
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  tags:
    - cis_5.1.1

- name: "CIS 5.1.2 - Ensure permissions on private host keys"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0600'
  tags:
    - cis_5.1.1

- name: "CIS 5.1.2 - Ensure permissions on public host keys"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ lookup('fileglob', '/etc/ssh/ssh_host_*_key.pub', wantlist=True) }}"
  tags:
    - cis_5.1.3

- name: "CIS 5.1 - Configure sshd settings"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    create: yes
    validate: '/usr/sbin/sshd -t -f %s'
  loop: "{{ cis_sshd_settings }}"
  notify: Restart sshd
  tags:
    - cis_5.1_hardening

- name: "CIS 5.1.7 - Configure SSH access control"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    lineinfile: "AllowUsers {{ cis_ssh_allowed_users | join (',') }}"
    validate: '/usr/sbin/sshd -t -f %s'
  when: cis_ssh_allowed_users is defined
  notify: Restart sshd
  tags:
    - cis_5.1.7

- name: "CIS 5.1.8 - Configure SSH banner"
  ansible.builtin.lineinfile:
    path: /etc/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart sshd
  tags:
    - cis_5.1.8
