---
- name: "CIS 5.1 - Configure SSH Server"
  import_tasks: tasks/5.1_ssh.yml

- name: "CIS 5.2 - Configure Privilege Escalation"
  import_tasks: tasks/5.2_privilege_escalation.yml

- name: "CIS 5.3.1-2 Configure PAM Software Packages, Configure authselect"
  import_tasks: tasks/5.3.1_2_pam.yml

- name: "CIS 5.3.3 PAM Continued"
  import_tasks: tasks/5.3_pam_cont.yml

- name: "CIS 5.4 User Accounts and Environment"
  import_tasks: tasks/5.4_useraccts.yml
