- name: "CIS 6.1.1 - Ensure AIDE is installed"
  ansible.builtin.dnf:
    name: aide
    state: present
  tags: cis_6.1.1

- name: "CIS 6.1.2 - Ensure AIDE check is scheduled"
  ansible.builtin.cron:
    name: "AIDE integrity check"
    user: root
    minute: 0
    hour: 3
    job: "/usr/sbin/aide --check"
  tags:
    - cis_6.1.2

- name: "CIS 6.1.3 - Ensure AIDE binary permissions are secure"
  ansible.builtin.file:
    path: /usr/sbin/aide
    owner: root
    group: root
    mode: '0755'
  tags:
    - cis_6.1.3
