- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Reload auditd
  ansible.builtin.command: augenrules --load

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
