cis_logging_backend: journald

cis_audit_rules:
  - "-w /etc/sudoers -p wa -k scope"
  - "-w /etc/sudoers.d -p wa -k scope"
  - "-a always, exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k user_emulation"
  - "-w /var/log/sudo.log -p wa -k sudo_log"
  - "-a always,exit -F arch=64 -S adjtimex,settimeofday -k time-change"
  - "-w /etc/localtime -p wa -k time-change"
  - "-w /etc/hosts -p wa -k network_mods"
  - "-a always,exit -F arch=b64 -S mount -k mounts"
  - "-w /var/run/utmp -p wa -k session"
  - "-w /var/log/wtmp -p wa -k logins"
  - "-w /var/log/btmp -p wa -k logins"
  - "-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -k delete"
  - "-w /etc/selinux -p wa -k mac-policy"
  - "-w /usr/bin/chcon -p x -k perm_mod"
  - "-w /usr/bin/setfacl -p x -k perm_mod"
  - "-w /usr/bin/chacl -p x -k perm_mod"
  - "-w /usr/sbin/usermod -p x -k usermod"
  - "-w /sbin/insmod -p x -k modules"
  - "-w /sbin/rmmod -p x -k modules"
  - "-w /sbin/modprobe -p x -k modules" 
