- name: "CIS 3.2 - Disable network kernel modules"
  block:

    - name: "Disable modules"
      ansible.builtin.lineinfile:
        path: "/etc/modprobe.d/{{ item }}.conf"
        line: "install {{ item }} /bin/true"
        create: yes
      loop: "{{ cis_3_2_disabled_modules }}"

    - name: "Blacklist modules"
      ansible.builtin.lineinfile:
        path: "/etc/modprobe.d/{{ item }}.conf"
        line: "blacklist {{ item }}"
        create: yes
      loop: "{{ cis_3_2_disabled_modules }}"

    - name: "Unload modules"
      ansible.builtin.command: "modprobe -r {{ item }}"
      ignore_errors: yes
      loop: "{{ cis_3_2_disabled_modules }}"

  tags:
    - cis_3.2
