- name: "Ensure systemd-journal-remote is installed"
  ansible.builtin.dnf:
    name: systemd-remote
    state: present
  when: cis_logging_backend == "journald"

# 6.2.2.1.2 Ensure systemd-journal-upload authentication is configured
# This is manual because it involves configuring authentication for remote
# uploads, likely using client certificates or keys to securely transmit journal
# logs.
# First we would have to configure a secure authentication mechanism using SSL/TLS # Secondly we would update the
# /etc/systemd/journal-remote.conf file to specify how the logs will be uploaded
# securely to a remote server
# This is typically done by setting server, certificate and private key in the
# config file

- name: "Ensure systemd-journal-upload is enabled and active"
  ansible.builtin.systemd:
    name: systemd-journal-upload
    enabled: yes
    state: started
  when: cis_logging_backend == "journald"

- name: "Ensure systemd-journal-remote service is not in use"
  ansible.builtin.systemd:
    name: systemd-journal-remote
    state: stopped
    enabled: no
  when: cis_logging_backend == "journald"

- name: "Ensure journald ForwardToSyslog is disabled"
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog'
    line: 'ForwardToSyslog=no'
    create: yes
  when: cis_logging_backend == "journald"

- name: "Ensure journald Compress is configured"
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Compress'
    line: 'Compress=yes'
    create: yes
  when: cis_logging_backend == "journald"

- name: Ensure journald Storage is configured
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Storage'
    line: 'Storage=persistent'
    create: yes
  when: cis_logging_backend == "journald"

- name: "CIS 6.2.4.1 - Ensure access to log files is configured"
  ansible.builtin.file:
    path: /var/log/journal
    owner: root
    group: systemd_journal
    mode: '2750'
    state: directory
    recurse: yes
  tags:
    - cis_6.2.4.1
