- name: "Ensure rsyslog is installed"
  ansible.builtin.dnf:
    name: rsyslog
    state: present
  when: cis_logging_backend == "rsyslog"

- name: "Ensure rsyslog service is enabled and active"
  ansible.builtin.systemd:
    name: rsyslog
    enabled: yes
    state: started
  when: cis_logging_backend == "rsyslog"

- name: "Ensure journald is configured to send logs to rsyslog"
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog'
    line: 'ForwardToSyslog=yes'
    create: yes
  when: cis_logging_backend == "rsyslog"

- name: "Ensure rsyslog log file creation mode is configured"
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0644'
    create: yes
  when: cis_logging_backend == "rsyslog"

- name: "Ensure rsyslog is not configured to receive logs from a remote client"
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^module(load="imudp")'
    state: absent
  when: cis_logging_backend == "rsyslog"
