- name: "CIS 3.3 - Configure network kernel parameters"
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf
  loop: "{{ cis_sysctl_settings }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - cis_3.3
